USER_AGENTS = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.6167.85 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0',
    'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36',
    'Mozilla/5.0 (iPad; CPU OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1',
    'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.86 Safari/537.36',
    ]
WORK_MODEL = {
    '1': 'Presencial', 
    '2': 'Remoto', 
    '3': 'Híbrido'
    }
KEYWORDS = [
    'Data Analyst', 
    'Cientista de Dados', 
    'Engenheiro de Dados', 
    'Data Scientist',
    'Data Engineer', 
    'Analista de Dados'
    ]
SKILLS_LIST = [
    'machine learning',
    'cloud computing',
    'artificial intelligence',
    'cloud',
    'visão computacional',
    'data warehouse',
    'tensorflow',
    'feature engineering',
    'programação',
    'kubernetes',
    'data visualization',
    'pln',
    'pipelines',
    'governança de dados',
    'gcp',
    'excel',
    'tableau',
    'adaptabilidade',
    'computer vision',
    'pensamento crítico',
    'azure',
    'computação em nuvem',
    'estatística',
    'ai',
    'r',
    'trabalho em equipe',
    'hadoop',
    'limpeza de dados',
    'arquitetura de dados',
    'data cleaning',
    'séries temporais',
    'postgresql',
    'business intelligence',
    'time series',
    'python',
    'data architecture',
    'a/b testing',
    'etl',
    'inteligência de negócios',
    'ciência de dados',
    'reinforcement learning',
    'natural language processing',
    'problem solving',
    'inteligência artificial',
    'colaboração',
    'aprendizado por reforço',
    'data wrangling',
    'engenharia de dados',
    'redes neurais',
    'airflow',
    'nosql',
    'data analysis',
    'data quality',
    'comunicação eficaz',
    'aprendizado de máquina',
    'pytorch',
    'mysql',
    'data pipeline',
    'nlp',
    'business analytics',
    'data engineering',
    'preditiva',
    'data science',
    'deep learning',
    'solução de problemas',
    'critical thinking',
    'nuvem',
    'big data',
    'data storytelling',
    'mineração de dados',
    'statistics',
    'stata',
    'sql',
    'data governance',
    'power bi',
    'data mining',
    'ia',
    'spark',
    'testes a/b',
    'análise de negócios',
    'api',
    'scikit-learn',
    'bi',
    'análise de dados',
    'predictive',
    'pandas',
    'docker',
    'visualização de dados',
    'aws',
    'processamento de linguagem natural',
    'matlab',
    'sql server',
    'numpy',
    'qualidade dos dados'
    ]