SKILLS_LIST = [
    'machine learning',
    'cloud computing',
    'artificial intelligence',
    'cloud',
    'visão computacional',
    'data warehouse',
    'tensorflow',
    'feature engineering',
    'programação',
    'kubernetes',
    'data visualization',
    'pln',
    'pipelines',
    'governança de dados',
    'gcp',
    'excel',
    'tableau',
    'adaptabilidade',
    'computer vision',
    'pensamento crítico',
    'azure',
    'computação em nuvem',
    'estatística',
    'ai',
    'r',
    'trabalho em equipe',
    'hadoop',
    'limpeza de dados',
    'arquitetura de dados',
    'data cleaning',
    'séries temporais',
    'postgresql',
    'business intelligence',
    'time series',
    'python',
    'data architecture',
    'a/b testing',
    'etl',
    'inteligência de negócios',
    'ciência de dados',
    'reinforcement learning',
    'natural language processing',
    'problem solving',
    'inteligência artificial',
    'colaboração',
    'aprendizado por reforço',
    'data wrangling',
    'engenharia de dados',
    'redes neurais',
    'airflow',
    'nosql',
    'data analysis',
    'data quality',
    'comunicação eficaz',
    'aprendizado de máquina',
    'pytorch',
    'mysql',
    'data pipeline',
    'nlp',
    'business analytics',
    'data engineering',
    'preditiva',
    'data science',
    'deep learning',
    'solução de problemas',
    'critical thinking',
    'nuvem',
    'big data',
    'data storytelling',
    'mineração de dados',
    'statistics',
    'stata',
    'sql',
    'data governance',
    'power bi',
    'data mining',
    'ia',
    'spark',
    'testes a/b',
    'análise de negócios',
    'api',
    'scikit-learn',
    'bi',
    'análise de dados',
    'predictive',
    'pandas',
    'docker',
    'visualização de dados',
    'aws',
    'processamento de linguagem natural',
    'matlab',
    'sql server',
    'numpy',
    'qualidade dos dados'
    ]