import re

ROLE_PATTERNS = {
    "project_manager": [re.compile(r"(project manager|gerente de projetos|gestor de projetos)", re.I)],
    "scrum_master": [re.compile(r"scrum master", re.I)],
    "product_owner": [re.compile(r"product owner|don[o]? de produto", re.I)],
    "pmo": [re.compile(r"\bPMO\b", re.I)],
    "agile_coach": [re.compile(r"(agile coach|coach ágil)", re.I)],
}

STANDARD_SKILL_MAP = {
    "jira": [r"\bjira\b"],
    "confluence": [r"\bconfluence\b"],
    "ms project": [r"\bms\s?project\b", r"\bmicrosoft project\b"],
    "excel": [r"\bexcel\b"],
    "trello": [r"\btrello\b"],
    "asana": [r"\basana\b"],
    "monday": [r"\bmonday.com\b", r"\bmonday\b"],
    "clickup": [r"\bclickup\b"],
    "pmo": [r"\bpmo\b"],
    "scrum": [r"\bscrum\b"],
    "kanban": [r"\bkanban\b"],
    "xp": [r"\bextreme programming\b", r"\bxp\b"],
    "agile": [r"\bagile\b"],
    "csm": [r"\bcertified scrum master\b", r"\bcsm\b"],
    "pmp": [r"\bpmp\b"],
    "prince2": [r"\bprince\s?2\b"],
    "okrs": [r"\bokr[s]?\b"],
}

SPECIAL_CASES = {
    "pmp": re.compile(r"\bPMP\b", re.I),
    "prince2": re.compile(r"\bPrince\s*2\b", re.I),
    "csm": re.compile(r"\bCSM\b", re.I),  # Certified Scrum Master
    "safe": re.compile(r"\bSAFe\b", re.I),  # Scaled Agile Framework
    "itil": re.compile(r"\bITIL\b", re.I),
    "cobit": re.compile(r"\bCOBIT\b", re.I),
    "certified_agile": re.compile(r"(ICP-ACC|ICP-ATF|ICAgile)", re.I),
}

BRAZILIAN_STATES = {
    'AC': 'Acre',
    'AL': 'Alagoas',
    'AP': 'Amapá',
    'AM': 'Amazonas',
    'BA': 'Bahia',
    'CE': 'Ceará',
    'DF': 'Distrito Federal',
    'ES': 'Espírito Santo',
    'GO': 'Goiás',
    'MA': 'Maranhão',
    'MT': 'Mato Grosso',
    'MS': 'Mato Grosso do Sul',
    'MG': 'Minas Gerais',
    'PA': 'Pará',
    'PB': 'Paraíba',
    'PR': 'Paraná',
    'PE': 'Pernambuco',
    'PI': 'Piauí',
    'RJ': 'Rio de Janeiro',
    'RN': 'Rio Grande do Norte',
    'RS': 'Rio Grande do Sul',
    'RO': 'Rondônia',
    'RR': 'Roraima',
    'SC': 'Santa Catarina',
    'SP': 'São Paulo',
    'SE': 'Sergipe',
    'TO': 'Tocantins',
}

REGION_CITIES = {
    'Rio Branco': 'AC',
    'Maceió': 'AL',
    'Macapá': 'AP',
    'Manaus': 'AM',
    'Salvador': 'BA',
    'Fortaleza': 'CE',
    'Brasília': 'DF',
    'Vitória': 'ES',
    'Goiânia': 'GO',
    'São Luís': 'MA',
    'Cuiabá': 'MT',
    'Campo Grande': 'MS',
    'Belo Horizonte': 'MG',
    'Belém': 'PA',
    'João Pessoa': 'PB',
    'Curitiba': 'PR',
    'Recife': 'PE',
    'Teresina': 'PI',
    'Rio De Janeiro': 'RJ',
    'Natal': 'RN',
    'Porto Alegre': 'RS',
    'Porto Velho': 'RO',
    'Boa Vista': 'RR',
    'Florianópolis': 'SC',
    'São Paulo': 'SP',
    'Aracaju': 'SE',
    'Palmas': 'TO',
    'Campinas': 'SP',
}
