STANDARD_SKILL_MAP = {
    'Solução de problemas': ['solução de problemas', 'problem solving'],
    'Pensamento crítico': ['critical thinking', 'pensamento crítico'],
    'Inteligência Artificial': ['ia', 'inteligência artificial', 
                                'artificial intelligence', 'ai'],
    'Machine Learning': ['machine learning', 'aprendizado de máquina'],
    'Cloud': ['cloud', 'nuvem', 'computação em nuvem', 'cloud computing', 'gcp',
              'azure'],
    'NLP' : ['natural language processing', 'processamento de linguagem natural',
             'pln', 'nlp'],
    'Visão computacional': ['visão computacional', 'computer vision'],
    'Feature engineering': ['feature engineering'],
    'Visualização de dados': ['data visualization', 'tableau', 'power bi', 
                              'visualização de dados'],
    'Programação': ['programação'],
    'GCP': ['gcp'],
    'Excel': ['excel'],
    'Tableau': ['tableau'],
    'Adaptabildiade': ['adaptabilidade'],
    'Azure': ['azure'],
    'Estatística': ['estatística', 'statistics'],
    'R': ['r'],
    'Trabalho em equipe': ['trabalho em equipe'],
    'Limpeza de dados': ['limpeza de dados', 'data cleaning'],
    'Arquitetura de dados': ['arquitetura de dados', 'data architecture'],
    'Séries temporais': ['séries temporais', 'time series'],
    'BI': ['business intelligence', 'inteligência de negócios'],
    'Python': ['python'],
    'Teste A/B': ['a/b'],
    'ETL': ['etl'],
    'Aprendizado por reforço': ['reinforcement learning'],
    'PostgreSQL': ['postgresql'],
    'Redes neurais': ['redes neurais'],
    'NoSQL': ['nosql'],
    'Airflow': ['airflow'],
    'Comunicação': ['comunicação'],
    'Tensorflow': ['tensorflow'],
    'Data Warehouse': ['data warehouse'],
    'Kubernetes': ['kubernetes'],
    'Pipeline': ['pipeline', 'data pipeline'],
    'Governança de dados': ['governança de dados', 'data governance'],
    'Hadoop': ['hadoop'],
    'Manipulação de dados': ['data wrangling', 'manipulação de dados'],
    'Qualidade dos dados': ['data quality', 'qualidade dos dados'],
    'PyTorch': ['pytorch'],
    'MySQL': ['mysql'],
    'Análise de negócios': ['business analytics', 'análise de negócios'],
    'Deep Learning': ['deep learning', 'aprendizado profundo'],
    'Big Data': ['big data'],
    'Data storytelling': ['storytelling'],
    'Mineração de dados': ['mineração de dados', 'data mining'],
    'Tensorflow': ['tensorflow'],
    'SQL': ['sql'],
    'Power BI': ['power bi'],
    'Spark': ['spark', 'pyspark'],
    'API': ['api'],
    'Scikit-learn': ['scikit-learn'],
    'Pandas': ['pandas'],
    'Docker': ['docker'],
    'AWS': ['aws'],
    'MATLAB': ['matlab'],
    'SQL Server': ['sql server'],
    'NumPy': ['numpy']
    }